<a href="https://colab.research.google.com/github/Raj171053/LendWise-AI-Governance-Program/blob/main/LendWise_Model_Audit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:


system_name = "LendWise AI-001 Credit Scoring"
record_count = 1000
production_approved = False

print(system_name)
print(record_count)
print(production_approved)

LendWise AI-001 Credit Scoring
1000
False

In [3]:

good_credit_count = 700
bad_credit_count = 300

total_records = good_credit_count + bad_credit_count

print("Good-credit records:", good_credit_count)
print("Bad-credit records:", bad_credit_count)
print("Total records:", total_records)

Good-credit records: 700
Bad-credit records: 300
Total records: 1000

In [4]:

assert total_records == 1000

print("Validation passed: total records match expectation.")

Validation passed: total records match expectation.

In [5]:

import pandas as pd

print("pandas imported successfully!")

pandas imported successfully!

In [6]:

import pandas as pd

sample_data = {
    "applicant_id": ["A001", "A002", "A003"],
    "credit_score": [720, 580, 650],
    "decision": ["Approve", "Review", "Approve"]
}

sample_df = pd.DataFrame(sample_data)

display(sample_df)

  applicant_id  credit_score decision
0         A001           720  Approve
1         A002           580   Review
2         A003           650  Approve

In [7]:

print("Number of rows and columns:")
print(sample_df.shape)

print("\nColumn names:")
print(sample_df.columns.tolist())

print("\nMissing values per column:")
display(sample_df.isna().sum())

Number of rows and columns:
(3, 3)

Column names:
['applicant_id', 'credit_score', 'decision']

Missing values per column:

applicant_id    0
credit_score    0
decision        0
dtype: int64

In [8]:

import pandas as pd

print("Ready to inspect the credit-risk dataset.")

Ready to inspect the credit-risk dataset.

In [9]:

url = (
    "https://archive.ics.uci.edu/ml/"
    "machine-learning-databases/statlog/german/german.data"
)

columns = [
    "checking_account", "duration_months", "credit_history",
    "purpose", "credit_amount", "savings_account",
    "employment_since", "installment_rate", "personal_status_sex",
    "other_debtors", "residence_since", "property",
    "age_years", "other_installment_plans", "housing",
    "existing_credits", "job", "dependents",
    "telephone", "foreign_worker", "credit_risk"
]

df = pd.read_csv(
    url,
    sep=r"\s+",
    header=None,
    names=columns
)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [10]:

print("Dataset shape:", df.shape)

print("\nFirst five rows:")
display(df.head())

print("\nMissing values:")
display(df.isna().sum().to_frame("missing_count"))

print("\nCredit-risk labels:")
display(df["credit_risk"].value_counts(dropna=False))

Dataset shape: (1000, 21)

First five rows:

,checking_account,duration_months,credit_history,purpose,credit_amount,savings_account,employment_since,installment_rate,personal_status_sex,other_debtors,...,property,age_years,other_installment_plans,housing,existing_credits,job,dependents,telephone,foreign_worker,credit_risk
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

Missing values:

                         missing_count
checking_account                     0
duration_months                      0
credit_history                       0
purpose                              0
credit_amount                        0
savings_account                      0
employment_since                     0
installment_rate                     0
personal_status_sex                  0
other_debtors                        0
residence_since                      0
property                             0
age_years                            0
other_installment_plans              0
housing                              0
existing_credits                     0
job                                  0
dependents                           0
telephone                            0
foreign_worker                       0
credit_risk                          0

Credit-risk labels:

credit_risk
1    700
2    300
Name: count, dtype: int64

In [11]:

# Check which target labels exist in the dataset
print("Original credit-risk labels:")
print(df["credit_risk"].value_counts().sort_index())

# Validate the labels before transforming them
assert set(df["credit_risk"].unique()) == {1, 2}

# Create a binary target variable
df["bad_credit"] = (df["credit_risk"] == 2).astype(int)

# Display the new target distribution
print("\nBinary target distribution:")
print(df["bad_credit"].value_counts().sort_index())

# Calculate the percentage of bad-credit records
bad_credit_percentage = df["bad_credit"].mean() * 100

print("\nBad-credit percentage:", round(bad_credit_percentage, 2), "%")

Original credit-risk labels:
credit_risk
1    700
2    300
Name: count, dtype: int64

Binary target distribution:
bad_credit
0    700
1    300
Name: count, dtype: int64

Bad-credit percentage: 30.0 %

In [12]:

# Count missing values in each column
missing_values = df.isna().sum()

print("Missing values by column:")
display(missing_values.to_frame(name="missing_count"))

print("\nTotal missing cells:", missing_values.sum())

Missing values by column:

                         missing_count
checking_account                     0
duration_months                      0
credit_history                       0
purpose                              0
credit_amount                        0
savings_account                      0
employment_since                     0
installment_rate                     0
personal_status_sex                  0
other_debtors                        0
residence_since                      0
property                             0
age_years                            0
other_installment_plans              0
housing                              0
existing_credits                     0
job                                  0
dependents                           0
telephone                            0
foreign_worker                       0
credit_risk                          0
bad_credit                           0

Total missing cells: 0

In [13]:

# Count completely duplicated rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [14]:

print("Data types:")
display(df.dtypes.to_frame(name="data_type"))

print("\nSummary of numerical columns:")
display(df.describe())

Data types:

                        data_type
checking_account           object
duration_months             int64
credit_history             object
purpose                    object
credit_amount               int64
savings_account            object
employment_since           object
installment_rate            int64
personal_status_sex        object
other_debtors              object
residence_since             int64
property                   object
age_years                   int64
other_installment_plans    object
housing                    object
existing_credits            int64
job                        object
dependents                  int64
telephone                  object
foreign_worker             object
credit_risk                 int64
bad_credit                  int64

Summary of numerical columns:

,duration_months,credit_amount,installment_rate,residence_since,age_years,existing_credits,dependents,credit_risk,bad_credit
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000,1.300000,0.300000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086,0.458487,0.458487
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000,1.000000,0.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000,1.000000,0.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000,1.000000,0.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000,2.000000,1.000000

In [15]:

# Select columns expected to contain numerical values
numeric_columns = [
    "duration_months",
    "credit_amount",
    "installment_rate",
    "residence_since",
    "age_years",
    "existing_credits",
    "dependents"
]

# Show the minimum and maximum values
display(df[numeric_columns].agg(["min", "max"]).T)

                  min    max
duration_months     4     72
credit_amount     250  18424
installment_rate    1      4
residence_since     1      4
age_years          19     75
existing_credits    1      4
dependents          1      2

In [16]:

categorical_columns = [
    "checking_account",
    "credit_history",
    "purpose",
    "personal_status_sex",
    "housing",
    "job"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].value_counts(dropna=False))

checking_account
checking_account
A14    394
A11    274
A12    269
A13     63
Name: count, dtype: int64

credit_history
credit_history
A32    530
A34    293
A33     88
A31     49
A30     40
Name: count, dtype: int64

purpose
purpose
A43     280
A40     234
A42     181
A41     103
A49      97
A46      50
A45      22
A44      12
A410     12
A48       9
Name: count, dtype: int64

personal_status_sex
personal_status_sex
A93    548
A92    310
A94     92
A91     50
Name: count, dtype: int64

housing
housing
A152    713
A151    179
A153    108
Name: count, dtype: int64

job
job
A173    630
A172    200
A174    148
A171     22
Name: count, dtype: int64

In [17]:

# Define the target
y = df["bad_credit"]

# Remove both target columns from the input features
X = df.drop(columns=["credit_risk", "bad_credit"])

print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)

print("\nFeature columns:")
print(X.columns.tolist())

print("\nTarget distribution:")
display(y.value_counts().sort_index())

Feature matrix shape: (1000, 20)
Target shape: (1000,)

Feature columns:
['checking_account', 'duration_months', 'credit_history', 'purpose', 'credit_amount', 'savings_account', 'employment_since', 'installment_rate', 'personal_status_sex', 'other_debtors', 'residence_since', 'property', 'age_years', 'other_installment_plans', 'housing', 'existing_credits', 'job', 'dependents', 'telephone', 'foreign_worker']

Target distribution:

bad_credit
0    700
1    300
Name: count, dtype: int64

In [18]:

# Check that inputs and target have matching row counts
assert len(X) == len(y)

# Check that target columns are not included in the features
assert "credit_risk" not in X.columns
assert "bad_credit" not in X.columns

# Check that the target contains only the expected values
assert set(y.unique()) == {0, 1}

print("Feature and target validation passed.")

Feature and target validation passed.

In [19]:

from sklearn.model_selection import train_test_split

print("Train/test split function imported.")

Train/test split function imported.

In [20]:

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("\nTraining target distribution:")
display(y_train.value_counts().sort_index())

print("\nTesting target distribution:")
display(y_test.value_counts().sort_index())

Training features: (800, 20)
Testing features: (200, 20)

Training target distribution:

bad_credit
0    560
1    240
Name: count, dtype: int64

Testing target distribution:

bad_credit
0    140
1     60
Name: count, dtype: int64

In [21]:

assert len(X_train) == 800
assert len(X_test) == 200

assert len(y_train) == len(X_train)
assert len(y_test) == len(X_test)

assert set(y_train.unique()) == {0, 1}
assert set(y_test.unique()) == {0, 1}

print("Train/test split validation passed.")

Train/test split validation passed.

In [22]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

print("Preprocessing tools imported successfully.")

Preprocessing tools imported successfully.

In [23]:

numeric_features = X_train.select_dtypes(
    include=["number"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    exclude=["number"]
).columns.tolist()

print("Number of numerical columns:", len(numeric_features))
print("Number of categorical columns:", len(categorical_features))

print("\nNumerical columns:")
print(numeric_features)

print("\nCategorical columns:")
print(categorical_features)

Number of numerical columns: 7
Number of categorical columns: 13

Numerical columns:
['duration_months', 'credit_amount', 'installment_rate', 'residence_since', 'age_years', 'existing_credits', 'dependents']

Categorical columns:
['checking_account', 'credit_history', 'purpose', 'savings_account', 'employment_since', 'personal_status_sex', 'other_debtors', 'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker']

In [24]:

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_transformer, numeric_features),
        ("categorical", categorical_transformer, categorical_features)
    ]
)

print("Preprocessing pipeline created.")

Preprocessing pipeline created.

In [25]:

X_train_processed = preprocessor.fit_transform(X_train)

print("Preprocessing fitted on training data.")
print("Processed training shape:", X_train_processed.shape)

Preprocessing fitted on training data.
Processed training shape: (800, 61)

In [26]:

X_test_processed = preprocessor.transform(X_test)

print("Test data transformed.")
print("Processed testing shape:", X_test_processed.shape)

Test data transformed.
Processed testing shape: (200, 61)

In [27]:

assert X_train_processed.shape[0] == len(y_train)
assert X_test_processed.shape[0] == len(y_test)

assert X_train_processed.shape[1] == X_test_processed.shape[1]

print("Preprocessing validation passed.")
print("Training rows:", X_train_processed.shape[0])
print("Testing rows:", X_test_processed.shape[0])
print("Encoded feature count:", X_train_processed.shape[1])

Preprocessing validation passed.
Training rows: 800
Testing rows: 200
Encoded feature count: 61

In [28]:

from sklearn.linear_model import LogisticRegression

print("Logistic regression imported successfully.")

Logistic regression imported successfully.

In [29]:

model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

model.fit(X_train_processed, y_train)

print("Baseline model trained successfully.")

Baseline model trained successfully.

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [30]:

y_pred = model.predict(X_test_processed)
y_prob = model.predict_proba(X_test_processed)[:, 1]

print("Number of predictions:", len(y_pred))
print("First 10 predicted labels:", y_pred[:10])
print("First 10 bad-credit probabilities:", y_prob[:10].round(3))

Number of predictions: 200
First 10 predicted labels: [0 0 1 1 0 0 0 0 0 0]
First 10 bad-credit probabilities: [0.219 0.105 0.614 0.515 0.155 0.112 0.22  0.126 0.492 0.139]

In [31]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler(with_mean=False)

X_train_scaled = scaler.fit_transform(X_train_processed)
X_test_scaled = scaler.transform(X_test_processed)

print("Training data scaled:", X_train_scaled.shape)
print("Testing data scaled:", X_test_scaled.shape)

Training data scaled: (800, 61)
Testing data scaled: (200, 61)

In [32]:

model = LogisticRegression(
    max_iter=5000,
    random_state=42
)

model.fit(X_train_scaled, y_train)

print("Scaled baseline model training completed.")

Scaled baseline model training completed.

In [33]:

print("Iterations used:", model.n_iter_[0])
print("Maximum iterations allowed:", model.max_iter)

if model.n_iter_[0] < model.max_iter:
    print("The model stopped before reaching the iteration limit.")
else:
    print("The model reached the iteration limit; investigate convergence.")

Iterations used: 74
Maximum iterations allowed: 5000
The model stopped before reaching the iteration limit.

In [34]:

y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

print("Number of predictions:", len(y_pred))
print("First 10 predicted labels:", y_pred[:10])
print("First 10 bad-credit probabilities:", y_prob[:10].round(3))

Number of predictions: 200
First 10 predicted labels: [0 0 1 1 0 0 0 0 1 0]
First 10 bad-credit probabilities: [0.19  0.099 0.63  0.523 0.15  0.096 0.213 0.102 0.501 0.12 ]

In [35]:

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("Evaluation metrics imported successfully.")

Evaluation metrics imported successfully.

In [36]:

print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))

print(
    "Precision for bad credit:",
    round(precision_score(y_test, y_pred, zero_division=0), 4)
)

print(
    "Recall for bad credit:",
    round(recall_score(y_test, y_pred, zero_division=0), 4)
)

print(
    "F1 score for bad credit:",
    round(f1_score(y_test, y_pred, zero_division=0), 4)
)

Accuracy: 0.775
Precision for bad credit: 0.6364
Recall for bad credit: 0.5833
F1 score for bad credit: 0.6087

In [37]:

cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

cm_df = pd.DataFrame(
    cm,
    index=["Actual good credit (0)", "Actual bad credit (1)"],
    columns=["Predicted good credit (0)", "Predicted bad credit (1)"]
)

display(cm_df)

print("\nDetailed classification report:")
print(classification_report(
    y_test,
    y_pred,
    labels=[0, 1],
    target_names=["Good credit", "Bad credit"],
    zero_division=0
))

                        Predicted good credit (0)  Predicted bad credit (1)
Actual good credit (0)                        120                        20
Actual bad credit (1)                          25                        35

Detailed classification report:
              precision    recall  f1-score   support

 Good credit       0.83      0.86      0.84       140
  Bad credit       0.64      0.58      0.61        60

    accuracy                           0.78       200
   macro avg       0.73      0.72      0.73       200
weighted avg       0.77      0.78      0.77       200

In [38]:

from sklearn.metrics import confusion_matrix

tn, fp, fn, tp = confusion_matrix(
    y_test,
    y_pred,
    labels=[0, 1]
).ravel()

false_positive_rate = fp / (fp + tn)
false_negative_rate = fn / (fn + tp)

print("True negatives:", tn)
print("False positives:", fp)
print("False negatives:", fn)
print("True positives:", tp)

print(
    "False-positive rate:",
    round(false_positive_rate, 4)
)

print(
    "False-negative rate:",
    round(false_negative_rate, 4)
)

True negatives: 120
False positives: 20
False negatives: 25
True positives: 35
False-positive rate: 0.1429
False-negative rate: 0.4167

In [39]:

demographic_columns = [
    "age_years",
    "personal_status_sex",
    "foreign_worker"
]

for column in demographic_columns:
    print(f"\nColumn: {column}")
    print("Unique values:", sorted(df[column].unique()))
    display(df[column].value_counts().to_frame("count"))

Column: age_years
Unique values: [np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(70), np.int64(74), np.int64(75)]

           count
age_years
27            51
26            50
23            48
24            44
28            43
25            41
30            40
35            40
36            39
31            38
29            37
32            34
33            33
34            32
37            29
22            27
40            25
38            24
42            22
39            21
46            18
44            17
41            17
43            17
47            17
45            15
21            14
49            14
20            14
50            12
48            12
54            10
57             9
52             9
63             8
51             8
55             8
53             7
61             7
60             6
66             5
65             5
58             5
64             5
74             4
67             3
56             3
59             3
68             3
19             2
75             2
62             2
70             1

Column: personal_status_sex
Unique values: ['A91', 'A92', 'A93', 'A94']

                     count
personal_status_sex
A93                    548
A92                    310
A94                     92
A91                     50

Column: foreign_worker
Unique values: ['A201', 'A202']

                count
foreign_worker
A201              963
A202               37

In [40]:

# Preserve the original test-set row indexes.
age_test = X_test["age_years"]

# Create exploratory age groups.
age_group_test = pd.Series(
    age_test.map(
        lambda age: "Under 25" if age < 25 else "25 and older"
    ),
    index=X_test.index,
    name="age_group"
)

print("Age-group counts in the test set:")
display(age_group_test.value_counts())

Age-group counts in the test set:

age_group
25 and older    161
Under 25         39
Name: count, dtype: int64

In [41]:

# Assemble actual labels, predictions and age groups.
audit_results = pd.DataFrame({
    "actual": y_test,
    "predicted": y_pred,
    "age_group": age_group_test
})

def calculate_group_metrics(group):
    tn, fp, fn, tp = confusion_matrix(
        group["actual"],
        group["predicted"],
        labels=[0, 1]
    ).ravel()

    fpr = fp / (fp + tn) if (fp + tn) > 0 else float("nan")
    fnr = fn / (fn + tp) if (fn + tp) > 0 else float("nan")

    return pd.Series({
        "sample_size": len(group),
        "good_credit_count": (group["actual"] == 0).sum(),
        "bad_credit_count": (group["actual"] == 1).sum(),
        "false_positives": fp,
        "false_negatives": fn,
        "false_positive_rate": fpr,
        "false_negative_rate": fnr
    })

age_fairness_results = (
    audit_results
    .groupby("age_group")
    .apply(calculate_group_metrics, include_groups=False)
)

display(age_fairness_results.round(4))

,sample_size,good_credit_count,bad_credit_count,false_positives,false_negatives,false_positive_rate,false_negative_rate
age_group,,,,,,,
25 and older,161.0,120.0,41.0,16.0,17.0,0.1333,0.4146
Under 25,39.0,20.0,19.0,4.0,8.0,0.2000,0.4211

In [42]:

for group_name, group in audit_results.groupby("age_group"):
    tn, fp, fn, tp = confusion_matrix(
        group["actual"],
        group["predicted"],
        labels=[0, 1]
    ).ravel()

    print(f"\n{group_name}")
    print({
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp,
        "FPR": fp / (fp + tn) if fp + tn else None,
        "FNR": fn / (fn + tp) if fn + tp else None
    })

25 and older
{'TN': np.int64(104), 'FP': np.int64(16), 'FN': np.int64(17), 'TP': np.int64(24), 'FPR': np.float64(0.13333333333333333), 'FNR': np.float64(0.4146341463414634)}

Under 25
{'TN': np.int64(16), 'FP': np.int64(4), 'FN': np.int64(8), 'TP': np.int64(11), 'FPR': np.float64(0.2), 'FNR': np.float64(0.42105263157894735)}

In [43]:

from statsmodels.stats.proportion import proportion_confint

def wilson_interval(errors, total):
    if total == 0:
        return (float("nan"), float("nan"))

    lower, upper = proportion_confint(
        count=errors,
        nobs=total,
        alpha=0.05,
        method="wilson"
    )

    return round(lower, 4), round(upper, 4)

print("Wilson confidence-interval function ready.")

Wilson confidence-interval function ready.

In [44]:

for group_name, group in audit_results.groupby("age_group"):
    tn, fp, fn, tp = confusion_matrix(
        group["actual"],
        group["predicted"],
        labels=[0, 1]
    ).ravel()

    fpr_ci = wilson_interval(fp, fp + tn)
    fnr_ci = wilson_interval(fn, fn + tp)

    print(f"\n{group_name}")
    print(f"FPR: {fp / (fp + tn):.4f}, 95% CI: {fpr_ci}")
    print(f"FNR: {fn / (fn + tp):.4f}, 95% CI: {fnr_ci}")

25 and older
FPR: 0.1333, 95% CI: (0.0838, 0.2056)
FNR: 0.4146, 95% CI: (0.2776, 0.5663)

Under 25
FPR: 0.2000, 95% CI: (0.0807, 0.416)
FNR: 0.4211, 95% CI: (0.2314, 0.6372)

In [45]:

from statsmodels.stats.proportion import confint_proportions_2indep

# Counts from the verified age-group confusion matrices.
# First group: under 25
fp_under25 = 4
good_under25 = 20

# Second group: age 25 and older
fp_older = 16
good_older = 120

fpr_under25 = fp_under25 / good_under25
fpr_older = fp_older / good_older

difference = fpr_under25 - fpr_older

ci_low, ci_high = confint_proportions_2indep(
    count1=fp_under25,
    nobs1=good_under25,
    count2=fp_older,
    nobs2=good_older,
    method="newcomb",
    compare="diff",
    alpha=0.05
)

print("Under-25 FPR:", round(fpr_under25, 4))
print("Age-25-and-older FPR:", round(fpr_older, 4))
print("Difference in FPR:", round(difference, 4))
print("Difference in percentage points:", round(difference * 100, 2))
print(
    "95% CI for difference:",
    (round(ci_low, 4), round(ci_high, 4))
)

Under-25 FPR: 0.2
Age-25-and-older FPR: 0.1333
Difference in FPR: 0.0667
Difference in percentage points: 6.67
95% CI for difference: (np.float64(-0.0729), np.float64(0.2883))

In [46]:

import pandas as pd

# Get the feature names created by the preprocessing pipeline
feature_names = preprocessor.get_feature_names_out()

# Extract logistic regression coefficients
coefficients = model.coef_[0]

# Create a table for interpretation
coefficient_table = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefficients
})

print("Number of feature names:", len(feature_names))
print("Number of coefficients:", len(coefficients))

display(coefficient_table.head(10))

Number of feature names: 61
Number of coefficients: 61

                             feature  coefficient
0           numeric__duration_months     0.331623
1             numeric__credit_amount     0.344646
2          numeric__installment_rate     0.396451
3           numeric__residence_since     0.011747
4                 numeric__age_years    -0.054696
5          numeric__existing_credits     0.088335
6                numeric__dependents     0.131920
7  categorical__checking_account_A11     0.328268
8  categorical__checking_account_A12     0.144489
9  categorical__checking_account_A13    -0.001458

In [47]:

# Features with the highest positive coefficients
top_positive = coefficient_table.sort_values(
    "coefficient",
    ascending=False
).head(10)

# Features with the most negative coefficients
top_negative = coefficient_table.sort_values(
    "coefficient",
    ascending=True
).head(10)

print("Top positive coefficients:")
display(top_positive)

print("\nTop negative coefficients:")
display(top_negative)

Top positive coefficients:

                                      feature  coefficient
2                   numeric__installment_rate     0.396451
1                      numeric__credit_amount     0.344646
46                 categorical__property_A124     0.344264
0                    numeric__duration_months     0.331623
7           categorical__checking_account_A11     0.328268
26           categorical__savings_account_A61     0.248751
23                   categorical__purpose_A46     0.220786
50                  categorical__housing_A151     0.219633
16                   categorical__purpose_A40     0.215668
47  categorical__other_installment_plans_A141     0.169937

Top negative coefficients:

                                      feature  coefficient
10          categorical__checking_account_A14    -0.430226
15            categorical__credit_history_A34    -0.283921
52                  categorical__housing_A153    -0.276650
17                   categorical__purpose_A41    -0.254644
30           categorical__savings_account_A65    -0.235845
29           categorical__savings_account_A64    -0.221793
34          categorical__employment_since_A74    -0.194521
38       categorical__personal_status_sex_A93    -0.187768
49  categorical__other_installment_plans_A143    -0.152694
43                 categorical__property_A121    -0.149627

In [48]:
# Display the original dataset's category codes and their counts
category_columns = [
    "checking_account",
    "credit_history",
    "purpose",
    "savings_account",
    "property",
    "housing"
]

for column in category_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts())

--- checking_account ---
checking_account
A14    394
A11    274
A12    269
A13     63
Name: count, dtype: int64

--- credit_history ---
credit_history
A32    530
A34    293
A33     88
A31     49
A30     40
Name: count, dtype: int64

--- purpose ---
purpose
A43     280
A40     234
A42     181
A41     103
A49      97
A46      50
A45      22
A44      12
A410     12
A48       9
Name: count, dtype: int64

--- savings_account ---
savings_account
A61    603
A65    183
A62    103
A63     63
A64     48
Name: count, dtype: int64

--- property ---
property
A123    332
A121    282
A122    232
A124    154
Name: count, dtype: int64

--- housing ---
housing
A152    713
A151    179
A153    108
Name: count, dtype: int64

In [49]:
# Join held-out predictions to the original housing categories
housing_test = X_test["housing"].reset_index(drop=True)

housing_audit = pd.DataFrame({
    "actual": y_test.reset_index(drop=True),
    "predicted": pd.Series(y_pred),
    "housing": housing_test
})

# Count records and calculate false-positive / false-negative rates
for category, group in housing_audit.groupby("housing"):
    tn = ((group["actual"] == 0) & (group["predicted"] == 0)).sum()
    fp = ((group["actual"] == 0) & (group["predicted"] == 1)).sum()
    fn = ((group["actual"] == 1) & (group["predicted"] == 0)).sum()
    tp = ((group["actual"] == 1) & (group["predicted"] == 1)).sum()

    fpr = fp / (fp + tn) if (fp + tn) else float("nan")
    fnr = fn / (fn + tp) if (fn + tp) else float("nan")

    print(
        f"Housing {category}: n={len(group)}, "
        f"FPR={fpr:.3f}, FNR={fnr:.3f}"
    )

Housing A151: n=35, FPR=0.364, FNR=0.231
Housing A152: n=143, FPR=0.095, FNR=0.500
Housing A153: n=22, FPR=0.154, FNR=0.333

In [50]:
for category, group in housing_audit.groupby("housing"):
    tn = ((group["actual"] == 0) & (group["predicted"] == 0)).sum()
    fp = ((group["actual"] == 0) & (group["predicted"] == 1)).sum()
    fn = ((group["actual"] == 1) & (group["predicted"] == 0)).sum()
    tp = ((group["actual"] == 1) & (group["predicted"] == 1)).sum()

    print(f"\nHousing category: {category}")
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")
    print(f"Actual good-credit cases: {tn + fp}")
    print(f"Actual bad-credit cases: {fn + tp}")

Housing category: A151
TN=14, FP=8, FN=3, TP=10
Actual good-credit cases: 22
Actual bad-credit cases: 13

Housing category: A152
TN=95, FP=10, FN=19, TP=19
Actual good-credit cases: 105
Actual bad-credit cases: 38

Housing category: A153
TN=11, FP=2, FN=3, TP=6
Actual good-credit cases: 13
Actual bad-credit cases: 9

In [51]:
# Select the first record from the existing test set
sample_index = 0

sample = X_test.iloc[[sample_index]]
actual_outcome = y_test.iloc[sample_index]
predicted_outcome = y_pred[sample_index]
predicted_probability = y_prob[sample_index]

print("Actual label:", actual_outcome)
print("Predicted label:", predicted_outcome)
print("Predicted probability of bad credit:", round(predicted_probability, 4))
print("\nInput features:")
display(sample.T)

Actual label: 0
Predicted label: 0
Predicted probability of bad credit: 0.1904

Input features:

                           30
checking_account          A12
duration_months            18
credit_history            A32
purpose                   A49
credit_amount            1913
savings_account           A64
employment_since          A72
installment_rate            3
personal_status_sex       A94
other_debtors            A101
residence_since             3
property                 A121
age_years                  36
other_installment_plans  A141
housing                  A152
existing_credits            1
job                      A173
dependents                  1
telephone                A192
foreign_worker           A201

In [54]:
# Calculate each transformed feature's contribution
sample_processed = preprocessor.transform(sample)
sample_scaled = scaler.transform(sample_processed)

contributions = sample_scaled[0] * model.coef_[0]

explanation = pd.DataFrame({
    "feature": preprocessor.get_feature_names_out(),
    "contribution": contributions
})

print("Model intercept:", round(model.intercept_[0], 4))
print("Sum of feature contributions:", round(contributions.sum(), 4))
print(
    "Total log-odds score:",
    round(model.intercept_[0] + contributions.sum(), 4)
)

print("\nLargest positive contributions:")
display(
    explanation.sort_values(
        "contribution", ascending=False
    ).head(5)
)

print("\nLargest negative contributions:")
display(
    explanation.sort_values(
        "contribution", ascending=True
    ).head(5)
)

Model intercept: -4.3034
Sum of feature contributions: 2.8562
Total log-odds score: -1.4472

Largest positive contributions:

                                      feature  contribution
2                   numeric__installment_rate      1.058386
59           categorical__foreign_worker_A201      0.716954
0                    numeric__duration_months      0.505440
47  categorical__other_installment_plans_A141      0.489749
6                         numeric__dependents      0.359842

Largest negative contributions:

                             feature  contribution
29  categorical__savings_account_A64     -1.005833
43        categorical__property_A121     -0.332794
4                 numeric__age_years     -0.178382
25          categorical__purpose_A49     -0.165521
58       categorical__telephone_A192     -0.162013

In [55]:
# Create copies without the foreign_worker feature
X_train_no_foreign = X_train.drop(columns=["foreign_worker"])
X_test_no_foreign = X_test.drop(columns=["foreign_worker"])

# Reuse the existing preprocessing design
numeric_no_foreign = X_train_no_foreign.select_dtypes(
    include=["number"]
).columns.tolist()

categorical_no_foreign = X_train_no_foreign.select_dtypes(
    exclude=["number"]
).columns.tolist()

preprocessor_no_foreign = ColumnTransformer(
    transformers=[
        ("numeric", numeric_transformer, numeric_no_foreign),
        ("categorical", categorical_transformer, categorical_no_foreign)
    ]
)

# Fit preprocessing on training data only
X_train_no_foreign_processed = preprocessor_no_foreign.fit_transform(
    X_train_no_foreign
)
X_test_no_foreign_processed = preprocessor_no_foreign.transform(
    X_test_no_foreign
)

# Scale using the same approach as the baseline
scaler_no_foreign = StandardScaler(with_mean=False)
X_train_no_foreign_scaled = scaler_no_foreign.fit_transform(
    X_train_no_foreign_processed
)
X_test_no_foreign_scaled = scaler_no_foreign.transform(
    X_test_no_foreign_processed
)

# Train the comparison model
model_no_foreign = LogisticRegression(
    max_iter=5000,
    random_state=42
)
model_no_foreign.fit(
    X_train_no_foreign_scaled,
    y_train
)

# Predict on the same held-out test set
y_pred_no_foreign = model_no_foreign.predict(
    X_test_no_foreign_scaled
)
y_prob_no_foreign = model_no_foreign.predict_proba(
    X_test_no_foreign_scaled
)[:, 1]

print("Original feature count:", X_train.shape[1])
print("Feature count without foreign_worker:", X_train_no_foreign.shape[1])
print("Comparison model trained successfully.")

Original feature count: 20
Feature count without foreign_worker: 19
Comparison model trained successfully.

In [56]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

def evaluate_model(name, y_true, predictions):
    tn, fp, fn, tp = confusion_matrix(
        y_true, predictions, labels=[0, 1]
    ).ravel()

    return {
        "Model": name,
        "Accuracy": accuracy_score(y_true, predictions),
        "Precision (bad credit)": precision_score(
            y_true, predictions, zero_division=0
        ),
        "Recall (bad credit)": recall_score(
            y_true, predictions, zero_division=0
        ),
        "F1 (bad credit)": f1_score(
            y_true, predictions, zero_division=0
        ),
        "FPR": fp / (fp + tn) if (fp + tn) else float("nan"),
        "FNR": fn / (fn + tp) if (fn + tp) else float("nan")
    }

comparison = pd.DataFrame([
    evaluate_model("Baseline — all features", y_test, y_pred),
    evaluate_model(
        "Without foreign_worker",
        y_test,
        y_pred_no_foreign
    )
])

display(comparison.round(4))

,Model,Accuracy,Precision (bad credit),Recall (bad credit),F1 (bad credit),FPR,FNR
0,Baseline — all features,0.775,0.6364,0.5833,0.6087,0.1429,0.4167
1,Without foreign_worker,0.780,0.6667,0.5333,0.5926,0.1143,0.4667

In [58]:
import numpy as np

In [59]:
# Compare group-level errors for both models
# Reuses existing test labels and predictions

def group_error_rates(y_true, y_predicted, groups, model_name):
    audit = pd.DataFrame({
        "actual": np.asarray(y_true),
        "predicted": np.asarray(y_predicted),
        "group": np.asarray(groups)
    })

    results = []

    for group_name, data in audit.groupby("group"):
        tn = ((data["actual"] == 0) & (data["predicted"] == 0)).sum()
        fp = ((data["actual"] == 0) & (data["predicted"] == 1)).sum()
        fn = ((data["actual"] == 1) & (data["predicted"] == 0)).sum()
        tp = ((data["actual"] == 1) & (data["predicted"] == 1)).sum()

        results.append({
            "Model": model_name,
            "Group": group_name,
            "N": len(data),
            "TN": tn,
            "FP": fp,
            "FN": fn,
            "TP": tp,
            "FPR": fp / (fp + tn) if (fp + tn) else np.nan,
            "FNR": fn / (fn + tp) if (fn + tp) else np.nan
        })

    return results


# Preserve the original category labels from the same held-out test rows
foreign_groups = X_test["foreign_worker"].reset_index(drop=True)

group_comparison = pd.DataFrame(
    group_error_rates(
        y_test, y_pred, foreign_groups, "Baseline"
    )
    +
    group_error_rates(
        y_test, y_pred_no_foreign, foreign_groups,
        "Without foreign_worker"
    )
)

display(group_comparison.round(4))

                    Model Group    N   TN  FP  FN  TP     FPR     FNR
0                Baseline  A201  194  115  20  25  34  0.1481  0.4237
1                Baseline  A202    6    5   0   0   1  0.0000  0.0000
2  Without foreign_worker  A201  194  119  16  28  31  0.1185  0.4746
3  Without foreign_worker  A202    6    5   0   0   1  0.0000  0.0000